version: 2
jobs:
  build34:
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV: py34
    steps:
      - checkout

      - restore_cache:
          keys:
            - build34-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
            - build34-{{ checksum ".circleci/requirements.txt" }}-
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install -r ./.circleci/requirements.txt
          tox -v
      - save_cache:
          key: build34-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - ".tox"
  build35:
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35
    steps:
      - checkout

      - restore_cache:
          keys:
            - build35-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
            - build35-{{ checksum ".circleci/requirements.txt" }}-
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install -r ./.circleci/requirements.txt
          tox -v
      - save_cache:
          key: build35-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - ".tox"
  build36:
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36
    steps:
      - checkout

      - restore_cache:
          keys:
            - build36-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
            - build36-{{ checksum ".circleci/requirements.txt" }}-
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install -r ./.circleci/requirements.txt
          tox -v
      - save_cache:
          key: build36-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - ".tox"
  build37:
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37
    steps:
      - checkout

      - restore_cache:
          keys:
            - build37-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
            - build37-{{ checksum ".circleci/requirements.txt" }}-
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install -r ./.circleci/requirements.txt
          tox -v
      - save_cache:
          key: build37-{{ checksum ".circleci/requirements.txt" }}-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - ".tox"
workflows:
  version: 2
  build:
    jobs:
      - build34
      - build35
      - build36
      - build37
