---
version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  tests:
    parameters:
      pythonversion:
        type: string
    executor:
      name: python/default
      tag: << parameters.pythonversion >>
    environment:
      ARTIFACTS: /tmp/python-jwt
    steps:
      - checkout: {}
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
          args: -r requirements-dev.txt
          pre-install-steps:
            - run: python3 -m pip install --upgrade pip
      - run:
          name: Run tests
          command: |
            mypy
            py.test \
              --verbose --capture=tee-sys \
              --junit-xml="${ARTIFACTS}/junit/jwt.xml" \
              --cov-report="html:${ARTIFACTS}/coverage" \
              jwt
      - store_artifacts:
          path: "/tmp/python-jwt"
      - store_test_results:
          path: "/tmp/python-jwt"
workflows:
  version: 2
  tests:
    jobs:
      - tests:
          matrix:
            parameters:
              pythonversion:
                - '3.6'
                - '3.7'
                - '3.8'
                - '3.9'
