---
version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:<< parameters.pythonversion >>
    parameters:
      pythonversion:
        type: string
    environment:
      ARTIFACTS: /tmp/python-jwt
    steps:
      - checkout: {}
      - restore_cache:
          key: pytest-v1-<< parameters.pythonversion >>-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
      - run:
          name: tox
          command: |
            if [ ! -d ".venv" ]; then
              python3 -m venv ./.venv
            fi
            . ./.venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r ./.circleci/requirements.txt

            tox -v -e circleci
      - save_cache:
          key: pytest-v1-<< parameters.pythonversion >>-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}
          paths:
            - ".tox"
            - ".venv"
      - store_artifacts:
          path: "/tmp/python-jwt"
      - store_test_results:
          path: "/tmp/python-jwt"
workflows:
  version: 2
  tests:
    jobs:
      - tests:
          matrix:
            parameters:
              pythonversion:
                - '3.5'
                - '3.6'
                - '3.7'
                - '3.8'
